from __future__ import annotations


APPLICATION_FILENAME = "DokumentenScannerSortierung.exe"
OPEN_LAUNCHER_FILENAME = "DokumentenScannerSortierung-Oeffnen.exe"
APPLICATION_FOLDER = "DokumentenScannerSortierung"
SHORTCUT_FILENAME = "Dokumenten-Scanner-Sortierung.lnk"
STARTUP_SHORTCUT_FILENAME = "Dokumenten-Scanner-Sortierung.lnk"
AUTOSTART_ARGUMENT = "--autostart"
NOTICE_FILENAME = "THIRD_PARTY_NOTICES.md"
ICON_FILENAME = "DokumentenScannerSortierung.ico"
PAYLOAD_ICON_FILENAME = "dokumenten-scanner-sortierung.ico"
VERSION_FILENAME = "version.txt"
PAYLOAD_MANIFEST_FILENAME = "payload-manifest.json"
UNINSTALLER_FILENAME = "DokumentenScannerSortierung-Deinstallieren.ps1"
PAYLOAD_UNINSTALLER_FILENAME = "uninstall.ps1"
LEGACY_UNINSTALLER_FILENAME = "DokumentenScannerSortierung-Deinstallieren.exe"
DISPLAY_NAME = "Dokumenten-Scanner-Sortierung"
PUBLISHER = "Simon Hagen – Glas Hagen"
SUPPORT_EMAIL = "simon.hagen@glashagen.de"
UNINSTALL_REGISTRY_PATH = r"Software\Microsoft\Windows\CurrentVersion\Uninstall\DokumentenScannerSortierung"
SETUP_MUTEX_NAME = r"Global\GlasHagen.DokumentenScannerSortierung.Setup"
SERVER_AUTOSTART_TASK_NAME = "GlasHagen Dokumenten-Scanner-Sortierung"
SERVER_SETTINGS_FOLDER = "DokumentenScannerSortierung"
SERVER_SETTINGS_FILENAME = "settings.json"

INSTALL_ACTION_INSTALL = "install"
INSTALL_ACTION_UPDATE = "update"
INSTALL_ACTION_REPAIR = "repair"
INSTALL_ACTION_DOWNGRADE = "downgrade"
INSTALL_ACTION_DOWNGRADE_BLOCKED = "downgrade_blocked"
INSTALL_ACTION_UNKNOWN_VERSION_BLOCKED = "unknown_version_blocked"
